#!/bin/bash

# GitHub Push Script for ACE CRM
echo "📦 Pushing ACE CRM to GitHub..."
echo ""
echo "⚠️  IMPORTANT: You need a GitHub Personal Access Token"
echo ""
echo "1️⃣  First, create your token:"
echo "   👉 Open: https://github.com/settings/tokens/new"
echo "   👉 Name: ACE CRM Deployment"
echo "   👉 Expiration: 30 days"
echo "   👉 Scopes: ✅ repo (Full control)"
echo "   👉 Click: Generate token"
echo "   👉 COPY the token (starts with ghp_)"
echo ""
echo "2️⃣  Then run this command:"
echo ""
echo "git push -u origin main"
echo ""
echo "3️⃣  When prompted:"
echo "   Username: rhyanalmeida"
echo "   Password: [PASTE YOUR TOKEN HERE]"
echo ""
echo "📝 Alternative: Set token in URL (one-time):"
echo "git remote set-url origin https://rhyanalmeida:YOUR_TOKEN@github.com/rhyanalmeida/theacewebcrm.git"
echo "git push -u origin main"
echo ""
echo "After pushing, remember to reset URL for security:"
echo "git remote set-url origin https://github.com/rhyanalmeida/theacewebcrm.git"