// Database type definitions for frontend
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          first_name: string;
          last_name: string;
          phone?: string;
          avatar_url?: string;
          timezone: string;
          language: string;
          status: 'active' | 'inactive' | 'suspended';
          email_verified: boolean;
          last_login_at?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          first_name: string;
          last_name: string;
          phone?: string;
          avatar_url?: string;
          timezone?: string;
          language?: string;
          status?: 'active' | 'inactive' | 'suspended';
          email_verified?: boolean;
          last_login_at?: string;
        };
        Update: {
          email?: string;
          first_name?: string;
          last_name?: string;
          phone?: string;
          avatar_url?: string;
          timezone?: string;
          language?: string;
          status?: 'active' | 'inactive' | 'suspended';
          email_verified?: boolean;
          last_login_at?: string;
        };
      };
      companies: {
        Row: {
          id: string;
          name: string;
          legal_name?: string;
          website?: string;
          industry?: string;
          company_size?: string;
          annual_revenue?: number;
          description?: string;
          logo_url?: string;
          address?: any;
          social_media?: any;
          status: 'active' | 'inactive' | 'prospect';
          owner_id?: string;
          created_by?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          legal_name?: string;
          website?: string;
          industry?: string;
          company_size?: string;
          annual_revenue?: number;
          description?: string;
          logo_url?: string;
          address?: any;
          social_media?: any;
          status?: 'active' | 'inactive' | 'prospect';
          owner_id?: string;
          created_by?: string;
        };
        Update: {
          name?: string;
          legal_name?: string;
          website?: string;
          industry?: string;
          company_size?: string;
          annual_revenue?: number;
          description?: string;
          logo_url?: string;
          address?: any;
          social_media?: any;
          status?: 'active' | 'inactive' | 'prospect';
          owner_id?: string;
        };
      };
      contacts: {
        Row: {
          id: string;
          company_id?: string;
          email?: string;
          first_name: string;
          last_name: string;
          title?: string;
          department?: string;
          phone?: string;
          mobile_phone?: string;
          avatar_url?: string;
          linkedin_url?: string;
          address?: any;
          birthday?: string;
          notes?: string;
          status: 'active' | 'inactive' | 'unqualified';
          lead_source?: string;
          owner_id?: string;
          created_by?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id?: string;
          email?: string;
          first_name: string;
          last_name: string;
          title?: string;
          department?: string;
          phone?: string;
          mobile_phone?: string;
          avatar_url?: string;
          linkedin_url?: string;
          address?: any;
          birthday?: string;
          notes?: string;
          status?: 'active' | 'inactive' | 'unqualified';
          lead_source?: string;
          owner_id?: string;
          created_by?: string;
        };
        Update: {
          company_id?: string;
          email?: string;
          first_name?: string;
          last_name?: string;
          title?: string;
          department?: string;
          phone?: string;
          mobile_phone?: string;
          avatar_url?: string;
          linkedin_url?: string;
          address?: any;
          birthday?: string;
          notes?: string;
          status?: 'active' | 'inactive' | 'unqualified';
          lead_source?: string;
          owner_id?: string;
        };
      };
      leads: {
        Row: {
          id: string;
          contact_id?: string;
          company_id?: string;
          title: string;
          description?: string;
          status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'negotiation' | 'won' | 'lost';
          priority: 'low' | 'medium' | 'high' | 'urgent';
          lead_source?: string;
          estimated_value?: number;
          estimated_close_date?: string;
          probability: number;
          next_action?: string;
          next_action_date?: string;
          owner_id?: string;
          created_by?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          contact_id?: string;
          company_id?: string;
          title: string;
          description?: string;
          status?: 'new' | 'contacted' | 'qualified' | 'proposal' | 'negotiation' | 'won' | 'lost';
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          lead_source?: string;
          estimated_value?: number;
          estimated_close_date?: string;
          probability?: number;
          next_action?: string;
          next_action_date?: string;
          owner_id?: string;
          created_by?: string;
        };
        Update: {
          contact_id?: string;
          company_id?: string;
          title?: string;
          description?: string;
          status?: 'new' | 'contacted' | 'qualified' | 'proposal' | 'negotiation' | 'won' | 'lost';
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          lead_source?: string;
          estimated_value?: number;
          estimated_close_date?: string;
          probability?: number;
          next_action?: string;
          next_action_date?: string;
          owner_id?: string;
        };
      };
      deals: {
        Row: {
          id: string;
          lead_id?: string;
          contact_id?: string;
          company_id?: string;
          title: string;
          description?: string;
          deal_type?: string;
          stage: 'discovery' | 'proposal' | 'negotiation' | 'contract' | 'project' | 'completed' | 'lost';
          value: number;
          currency: string;
          close_date?: string;
          probability: number;
          next_action?: string;
          next_action_date?: string;
          won_reason?: string;
          lost_reason?: string;
          competitor?: string;
          owner_id?: string;
          created_by?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lead_id?: string;
          contact_id?: string;
          company_id?: string;
          title: string;
          description?: string;
          deal_type?: string;
          stage?: 'discovery' | 'proposal' | 'negotiation' | 'contract' | 'project' | 'completed' | 'lost';
          value: number;
          currency?: string;
          close_date?: string;
          probability?: number;
          next_action?: string;
          next_action_date?: string;
          won_reason?: string;
          lost_reason?: string;
          competitor?: string;
          owner_id?: string;
          created_by?: string;
        };
        Update: {
          lead_id?: string;
          contact_id?: string;
          company_id?: string;
          title?: string;
          description?: string;
          deal_type?: string;
          stage?: 'discovery' | 'proposal' | 'negotiation' | 'contract' | 'project' | 'completed' | 'lost';
          value?: number;
          currency?: string;
          close_date?: string;
          probability?: number;
          next_action?: string;
          next_action_date?: string;
          won_reason?: string;
          lost_reason?: string;
          competitor?: string;
          owner_id?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          deal_id?: string;
          company_id?: string;
          contact_id?: string;
          name: string;
          description?: string;
          project_type?: string;
          status: 'planned' | 'active' | 'on_hold' | 'completed' | 'cancelled';
          priority: 'low' | 'medium' | 'high' | 'urgent';
          start_date?: string;
          due_date?: string;
          completion_date?: string;
          budget?: number;
          hours_estimated?: number;
          hours_actual?: number;
          project_manager_id?: string;
          team_members?: string[];
          tags?: string[];
          custom_fields?: any;
          created_by?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          deal_id?: string;
          company_id?: string;
          contact_id?: string;
          name: string;
          description?: string;
          project_type?: string;
          status?: 'planned' | 'active' | 'on_hold' | 'completed' | 'cancelled';
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          start_date?: string;
          due_date?: string;
          completion_date?: string;
          budget?: number;
          hours_estimated?: number;
          hours_actual?: number;
          project_manager_id?: string;
          team_members?: string[];
          tags?: string[];
          custom_fields?: any;
          created_by?: string;
        };
        Update: {
          deal_id?: string;
          company_id?: string;
          contact_id?: string;
          name?: string;
          description?: string;
          project_type?: string;
          status?: 'planned' | 'active' | 'on_hold' | 'completed' | 'cancelled';
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          start_date?: string;
          due_date?: string;
          completion_date?: string;
          budget?: number;
          hours_estimated?: number;
          hours_actual?: number;
          project_manager_id?: string;
          team_members?: string[];
          tags?: string[];
          custom_fields?: any;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}